version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: futebola-postgres
    environment:
      POSTGRES_DB: futebola_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
