services:
  db:
    image: postgres:15
    container_name: futebola_postgres
    environment:
      POSTGRES_DB: futebola_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - futebola-network

#  app:
#    build: .
#    container_name: futebola_app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/futebola_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 123456
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    depends_on:
#      - db
#    networks:
#      - futebola-network

volumes:
  postgres_data:

networks:
  futebola-network: