@userId = 4bd70cc6-b0f0-4104-99b0-4ef4c53023e4

### Get All payments
GET http://localhost:8080/payments

### Get User By ID
# Substitua o UUID abaixo pelo ID gerado na criação
GET http://localhost:8080/payments/{{userId}}

### Create payment
# Rota para criar um novo pagamento
POST http://localhost:8080/payments
Content-Type: application/json

{
  "playerId": "1651758c-e983-459e-9fca-13d5df607da9",
  "amount": 150.00,
  "paymentDate": "2025-06-21",
  "paymentType": "PIX",
  "paymentCategory": "ONE_TIME",
  "description": "Pagamento avulso por PIX"
}

### Update User
# Primeiro defina o userId acima com o ID gerado ao criar o usuário
PUT http://localhost:8080/payments/{{userId}}
Content-Type: application/json

{
  "amount": 50.0,
  "paymentDate": "2025-06-21",
  "paymentType": "PIX",
  "description": "Mensalidade junho",
  "playerId": "UUID-DO-JOGADOR"
}

### Delete User
# Substitua o UUID abaixo pelo ID gerado na criação
DELETE http://localhost:8080/payments/{{userId}}
