@userId = 820e9032-f009-4069-b306-9af3402815a6

### Get All payments
GET http://localhost:8080/payments

### Get User By ID
# Substitua o UUID abaixo pelo ID gerado na criação
GET http://localhost:8080/payments/{{userId}}

### Create payment
# Rota para criar um novo pagamento
POST http://localhost:8080/payments
Content-Type: application/json

{
  "playerId": "1651758c-e983-459e-9fca-13d5df607da9",
  "amount": "150.00",
  "paymentDate": "2025-06-21",
  "paymentType": "PIX",
  "paymentCategory": "ONE_TIME",
  "description": "Pagamento avulso por PIX"
}

### Update User
# Primeiro defina o userId acima com o ID gerado ao criar o usuário
PATCH http://localhost:8080/payments/{{userId}}
Content-Type: application/json

{
  "amount": 200.50,
  "paymentDate": "2025-06-22",
  "paymentType": "CREDIT_CARD",
  "paymentCategory": "RECURRING",
  "description": "Atualização do pagamento",
  "paymentStatus": "VALID"
}

### Delete User
# Substitua o UUID abaixo pelo ID gerado na criação
DELETE http://localhost:8080/payments/{{userId}}
