@userId = 4bd70cc6-b0f0-4104-99b0-4ef4c53023e4

### Get All Users
GET http://localhost:8080/users

### Get User By ID
# Substitua o UUID abaixo pelo ID gerado na criação
GET http://localhost:8080/users/{{userId}}

### Create User
# Rota da API para criar um novo usuario
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Marcel 2",
  "nickname": "Zagueiro Louco 3",
  "birthDate": "1995-03-03",
  "phone": "147999999999"
}

### Update User
# Primeiro defina o userId acima com o ID gerado ao criar o usuário
PUT http://localhost:8080/users/{{userId}}
Content-Type: application/json

{
  "name": "Alex Atualizado",
  "nickname": "Brabo Atualizado",
  "birthDate": "1990-01-01",
  "phone": "11988887777",
  "email": "alex.atualizado@futebola.com"
}

### Delete User
# Substitua o UUID abaixo pelo ID gerado na criação
DELETE http://localhost:8080/users/{{userId}}
