@paymentId = 820e9032-f009-4069-b306-9af3402815a6
@playerId = 1651758c-e983-459e-9fca-13d5df607da9
@groupId = 88b98f5f-2d71-4ef4-80c0-8f166da924f9

### 🔎 Get All Payments
GET http://localhost:8080/payments

### 🔎 Get Payment by ID
GET http://localhost:8080/payments/{{paymentId}}

### ➕ Create Payment
POST http://localhost:8080/payments
Content-Type: application/json

{
  "playerId": "{{playerId}}",
  "amount": 150.00,
  "paymentDate": "2025-06-21",
  "paymentType": "PIX",
  "paymentCategory": "ONE_TIME",
  "description": "Pagamento avulso por PIX",
  "groupId": "{{groupId}}"
}

### 🛠️ Atualizar pagamento completo
PATCH http://localhost:8080/payments/{{paymentId}}
Content-Type: application/json

{
  "amount": 200.50,
  "paymentDate": "2025-06-22",
  "paymentType": "CREDIT_CARD",
  "paymentCategory": "RECURRING",
  "description": "Atualização do pagamento",
  "paymentStatus": "VALID",
  "groupId": "{{groupId}}"
}

### ✏️ Atualizar apenas um campo
PATCH http://localhost:8080/payments/{{paymentId}}
Content-Type: application/json

{
  "description": "Pagamento após vencimento"
}

### ❌ Delete Payment
DELETE http://localhost:8080/payments/{{paymentId}}
